apiVersion: v2
name: engine
version: 1.0.0
appVersion: 0.9.0
description: Anchore container analysis and policy evaluation engine service
keywords:
  - analysis
  - docker
  - anchore
  - "anchore-engine"
  - image
  - security
  - vulnerability
  - scanner
home: https://anchore.com
sources:
  - https://github.com/anchore/anchore-engine
maintainers:
  - name: zhill
    email: zach@anchore.com
  - name: btodhunter
    email: bradyt@anchore.com
  - name: rprince
    email: robert.prince@anchore.com
engine: gotpl
icon: https://anchore.com/wp-content/uploads/2016/08/anchore.png
dependencies:
  - name: postgresql
    repository: "https://charts.bitnami.com/bitnami"
    version: "10.2.0"
    condition: postgresql.enabled